### Obtener todas las tareas
GET http://localhost:3000/api/tareas


### Crear una tarea
POST http://localhost:3000/api/tareas
Content-Type: application/json

{
  "titulo": "Configurar Data Center"
}


### Actualizar tarea
PUT http://localhost:3000/api/tareas/1
Content-Type: application/json

{
  "titulo": "Tarea actualizada",
  "completada": true
}


### Eliminar tarea
DELETE http://localhost:3000/api/tareas/1