name: Deploy VPS

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Actualizar VPS
        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.VPS_HOST }}

          username: ${{ secrets.VPS_USER }}

          key: ${{ secrets.VPS_SSH_KEY }}

          script: |

            cd ~/DatacenterCRUD

            echo "Actualizando codigo..."
            git pull origin main


            echo "Actualizando Backend..."

            cd backend

            npm install

            pm2 restart all


            echo "Actualizando Frontend..."

            cd ../frontend

            npm install

            npm run build


            echo "Buscando cambio en build..."

            grep -r "CI/CD" dist || echo "No encontrado"


            echo "Copiando frontend a Nginx..."

            sudo rm -rf /var/www/html/*

            sudo cp -r dist/* /var/www/html/


            echo "Despliegue completado"